# Generated by Django 2.1.4 on 2019-03-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filamentcolors', '0005_auto_20190303_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swatch',
            old_name='purchase_link',
            new_name='amazon_purchase_link',
        ),
        migrations.AddField(
            model_name='swatch',
            name='mfr_purchase_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
