# Generated by Django 2.1.4 on 2019-03-04 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0006_auto_20190303_1936"),
    ]

    operations = [
        migrations.RemoveField(model_name="swatch", name="bed_temp_str",),
        migrations.RemoveField(model_name="swatch", name="filament_type_str",),
        migrations.RemoveField(model_name="swatch", name="hot_end_temp_str",),
        migrations.RemoveField(model_name="swatch", name="manufacturer_str",),
    ]
