# Generated by Django 2.1.4 on 2019-03-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filamentcolors', '0007_auto_20190304_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swatch',
            name='card_img_jpeg',
            field=models.ImageField(blank=True, null=True, upload_to='card_img', verbose_name='DO NOT ADD! Computed card original'),
        ),
    ]
