# Generated by Django 2.1.4 on 2019-11-04 03:43

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0012_auto_20191104_0316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swatch",
            name="color_parent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WHT", "White"),
                    ("BLK", "Black"),
                    ("RED", "Red"),
                    ("GRN", "Green"),
                    ("YLW", "Yellow"),
                    ("BLU", "Blue"),
                    ("BRN", "Brown"),
                    ("PPL", "Purple"),
                    ("PNK", "Pink"),
                    ("RNG", "Orange"),
                    ("GRY", "Grey"),
                    ("TRN", "Transparent"),
                ],
                default="WHT",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="swatch",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
