# Generated by Django 2.1.4 on 2019-12-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0013_auto_20191104_0343"),
    ]

    operations = [
        migrations.RemoveField(model_name="swatch", name="maker",),
        migrations.RemoveField(model_name="swatch", name="printed_on",),
    ]
