# Generated by Django 3.0.4 on 2020-03-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filamentcolors', '0014_auto_20191219_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='swatch',
            name='rebuild_long_way',
            field=models.BooleanField(default=False, verbose_name='Regenerate the color information using the long way for increased accuracy.'),
        ),
        migrations.AlterField(
            model_name='swatch',
            name='regenerate_info',
            field=models.BooleanField(default=False, verbose_name='Rebuild all the information related to this swatch.'),
        ),
    ]
