# Generated by Django 3.0.4 on 2020-06-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0015_auto_20200327_0106"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Printer",
        ),
    ]
