# Generated by Django 3.0.4 on 2020-06-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filamentcolors', '0016_delete_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='swatch',
            name='published',
            field=models.BooleanField(default=True, help_text='Is the swatch visible on the homepage?'),
        ),
    ]
