# Generated by Django 3.0.4 on 2020-06-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0018_auto_20200619_0202"),
    ]

    operations = [
        migrations.AddField(
            model_name="swatch",
            name="donated_by",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
