# Generated by Django 3.0.4 on 2020-07-20 04:23

from django.db import migrations, models
import django.utils.timezone
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('filamentcolors', '0019_swatch_donated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('subtitle', models.CharField(blank=True, max_length=39, null=True)),
                ('body', martor.models.MartorField()),
                ('slug', models.SlugField(default='', editable=False, max_length=70)),
                ('published', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
