# Generated by Django 3.0.4 on 2020-07-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filamentcolors', '0019_swatch_donated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('slug', models.SlugField(default='', editable=False, max_length=70)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
