# Generated by Django 3.0.4 on 2020-07-03 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filamentcolors', '0020_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
