# Generated by Django 3.0.4 on 2020-07-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filamentcolors', '0021_post_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(blank=True, max_length=39, null=True),
        ),
    ]
