# Generated by Django 3.2.12 on 2022-03-24 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filamentcolors', '0023_auto_20211015_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swatch',
            name='tags',
        ),
    ]
