# Generated by Django 4.1.1 on 2022-10-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0024_remove_swatch_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pantone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=48)),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("rgb_r", models.IntegerField()),
                ("rgb_g", models.IntegerField()),
                ("rgb_b", models.IntegerField()),
                ("hex_color", models.CharField(blank=True, max_length=6, null=True)),
                ("category", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="RAL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=48)),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("rgb_r", models.IntegerField()),
                ("rgb_g", models.IntegerField()),
                ("rgb_b", models.IntegerField()),
                ("hex_color", models.CharField(blank=True, max_length=6, null=True)),
                ("category", models.CharField(max_length=30)),
            ],
        ),
    ]
