# Generated by Django 4.1.1 on 2022-10-12 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0025_pantone_ral"),
    ]

    operations = [
        migrations.AddField(
            model_name="swatch",
            name="closest_pantone_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pantone_1",
                to="filamentcolors.pantone",
                verbose_name="Computed Pantone 'Fashion and Interior Designers' color",
            ),
        ),
        migrations.AddField(
            model_name="swatch",
            name="closest_pantone_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pantone_2",
                to="filamentcolors.pantone",
                verbose_name="Computed Pantone 'Industrial Designers' color",
            ),
        ),
        migrations.AddField(
            model_name="swatch",
            name="closest_pantone_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pantone_3",
                to="filamentcolors.pantone",
                verbose_name="Computed Pantone 'Graphic Designers' color",
            ),
        ),
        migrations.AddField(
            model_name="swatch",
            name="closest_ral_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ral_1",
                to="filamentcolors.ral",
                verbose_name="Computed RAL Classic color",
            ),
        ),
        migrations.AddField(
            model_name="swatch",
            name="closest_ral_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ral_2",
                to="filamentcolors.ral",
                verbose_name="Computed RAL Effect color",
            ),
        ),
        migrations.AddField(
            model_name="swatch",
            name="closest_ral_3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ral_3",
                to="filamentcolors.ral",
                verbose_name="Computed RAL Design System+ color",
            ),
        ),
    ]
