# Generated by Django 4.1.1 on 2022-11-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0027_swatch_rgb_b_swatch_rgb_g_swatch_rgb_r_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericfile",
            name="name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="swatch",
            name="color_parent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WHT", "White"),
                    ("BLK", "Black"),
                    ("RED", "Red"),
                    ("GRN", "Green"),
                    ("YLW", "Yellow"),
                    ("BLU", "Blue"),
                    ("BRN", "Brown"),
                    ("PPL", "Purple"),
                    ("PNK", "Pink"),
                    ("RNG", "Orange"),
                    ("GRY", "Grey"),
                    ("TRN", "Translucent"),
                ],
                default="WHT",
                max_length=3,
                null=True,
            ),
        ),
    ]
