# Generated by Django 4.1.5 on 2023-01-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0030_alter_swatch_hex_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="swatch",
            name="date_published",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
