# Generated by Django 4.2.7 on 2023-11-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0033_alter_swatch_alt_color_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericfile",
            name="alt_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
