# Generated by Django 4.2.7 on 2023-11-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0034_genericfile_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="swap_purchase_buttons",
            field=models.BooleanField(
                default=False,
                help_text="List the manufacturer puchase link above the Amazon button.",
            ),
        ),
    ]
