# Generated by Django 4.2.7 on 2023-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0035_manufacturer_swap_purchase_buttons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="swap_purchase_buttons",
            field=models.BooleanField(
                default=False,
                help_text="List the manufacturer purchase link above the Amazon button.",
            ),
        ),
    ]
