# Generated by Django 5.0 on 2024-01-24 14:54

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0037_manufacturer_affiliate_portal_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="swatch",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
