# Generated by Django 5.0.1 on 2024-01-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0038_swatch_tags"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
