# Generated by Django 5.0.2 on 2024-02-16 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0040_manufacturer_parent_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Retailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("website", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "affiliate_url_param",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=2000, null=True)),
                (
                    "swatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filamentcolors.swatch",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filamentcolors.retailer",
                    ),
                ),
            ],
        ),
    ]
