# Generated by Django 5.0.4 on 2024-04-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "filamentcolors",
            "0043_remove_swatch_complement_hex_swatch_closest_pms_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="genericfilamenttype",
            name="slug",
            field=models.SlugField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="slug",
            field=models.SlugField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="swatch",
            name="slug",
            field=models.SlugField(blank=True, max_length=400, null=True),
        ),
    ]
