# Generated by Django 5.0.4 on 2024-05-12 05:44

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0046_swatch_td_usersubmittedtd"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="swatch",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
