# Generated by Django 5.0.4 on 2024-05-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0047_alter_swatch_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubmittedtd",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
