# Generated by Django 5.1.3 on 2024-12-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0049_deadlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="swatch",
            name="image_opengraph",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
