# Generated by Django 5.1.4 on 2024-12-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0050_swatch_image_opengraph"),
    ]

    operations = [
        migrations.AddField(
            model_name="swatch",
            name="posted_to_social_media",
            field=models.BooleanField(default=False),
        ),
    ]
