# Generated by Django 5.1.4 on 2025-01-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0051_swatch_posted_to_social_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="swatch",
            name="lab_a",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="swatch",
            name="lab_b",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="swatch",
            name="lab_l",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
