# Generated by Django 5.2.4 on 2025-07-15 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0053_swatch_computed_lab"),
    ]

    operations = [
        migrations.AddField(
            model_name="swatch",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced",
                to="filamentcolors.swatch",
            ),
        ),
    ]
