# Generated by Django 5.2.5 on 2025-09-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0054_swatch_replaced_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filamenttype",
            name="name",
            field=models.CharField(default="PLA", max_length=50),
        ),
    ]
