# Generated by Django 5.2.5 on 2025-09-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0055_alter_filamenttype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pantone",
            name="lab_a",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pantone",
            name="lab_b",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pantone",
            name="lab_l",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pantonepms",
            name="lab_a",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pantonepms",
            name="lab_b",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pantonepms",
            name="lab_l",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ral",
            name="lab_a",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ral",
            name="lab_b",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ral",
            name="lab_l",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
