# Generated by Django 5.2.9 on 2026-01-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0057_auto_20250925_0218"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="awin_affiliate_id",
            field=models.CharField(
                blank=True,
                help_text="Awin affiliate ID for tracking. If this is provided, urls will be rebuilt in the Awin format.",
                max_length=150,
                null=True,
            ),
        ),
    ]
