# Generated by Django 6.0.3 on 2026-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filamentcolors", "0059_sociallink"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="variant",
            field=models.CharField(
                choices=[
                    ("success", "success"),
                    ("danger", "danger"),
                    ("warning", "warning"),
                    ("info", "info"),
                    ("primary", "primary"),
                    ("secondary", "secondary"),
                    ("light", "light"),
                    ("dark", "dark"),
                ],
                default="primary",
                max_length=10,
            ),
        ),
    ]
