OBSERVER_ANGLE = "10"
ILLUMINANT = "d65"
LAB = {
    "L": {
        "min": 0,
        "max": 100,
    },
    "A": {
        "min": -128,
        "max": 127,
    },
    "B": {
        "min": -128,
        "max": 127,
    },
}

WHITE = "WHT"
BLACK = "BLK"
RED = "RED"
GREEN = "GRN"
YELLOW = "YLW"
BLUE = "BLU"
BROWN = "BRN"
PURPLE = "PPL"
PINK = "PNK"
ORANGE = "RNG"
GREY = "GRY"
TRANSLUCENT = "TRN"


NAMED_COLORS = {
    "aliceblue": "#F0F8FF",
    "antiquewhite": "#FAEBD7",
    "aqua": "#00FFFF",
    "aquamarine": "#7FFFD4",
    "azure": "#F0FFFF",
    "beige": "#F5F5DC",
    "bisque": "#FFE4C4",
    "black": "#000000",
    "blanchedalmond": "#FFEBCD",
    "blue": "#0000FF",
    "blueviolet": "#8A2BE2",
    "brown": "#A52A2A",
    "burlywood": "#DEB887",
    "cadetblue": "#5F9EA0",
    "chartreuse": "#7FFF00",
    "chocolate": "#D2691E",
    "coral": "#FF7F50",
    "cornflowerblue": "#6495ED",
    "cornsilk": "#FFF8DC",
    "crimson": "#DC143C",
    "cyan": "#00FFFF",
    "darkblue": "#00008B",
    "darkcyan": "#008B8B",
    "darkgoldenrod": "#B8860B",
    "darkgrey": "#A9A9A9",
    "darkgreen": "#006400",
    "darkkhaki": "#BDB76B",
    "darkmagenta": "#8B008B",
    "darkolivegreen": "#556B2F",
    "darkorange": "#FF8C00",
    "darkorchid": "#9932CC",
    "darkred": "#8B0000",
    "darksalmon": "#E9967A",
    "darkseagreen": "#8FBC8F",
    "darkslateblue": "#483D8B",
    "darkslategrey": "#2F4F4F",
    "darkturquoise": "#00CED1",
    "darkviolet": "#9400D3",
    "deeppink": "#FF1493",
    "deepskyblue": "#00BFFF",
    "dimgray": "#696969",
    "dodgerblue": "#1E90FF",
    "firebrick": "#B22222",
    "floralwhite": "#FFFAF0",
    "forestgreen": "#228B22",
    "fuchsia": "#FF00FF",
    "gainsboro": "#DCDCDC",
    "ghostwhite": "#F8F8FF",
    "gold": "#FFD700",
    "goldenrod": "#DAA520",
    "gray": "#808080",
    "green": "#008000",
    "greenyellow": "#ADFF2F",
    "honeydew": "#F0FFF0",
    "hotpink": "#FF69B4",
    "indianred": "#CD5C5C",
    "indigo": "#4B0082",
    "ivory": "#FFFFF0",
    "khaki": "#F0E68C",
    "lavender": "#E6E6FA",
    "lavenderblush": "#FFF0F5",
    "lawngreen": "#7CFC00",
    "lemonchiffon": "#FFFACD",
    "lightblue": "#ADD8E6",
    "lightcoral": "#F08080",
    "lightcyan": "#E0FFFF",
    "lightgoldenrodyellow": "#FAFAD2",
    "lightgrey": "#D3D3D3",
    "lightgreen": "#90EE90",
    "lightpink": "#FFB6C1",
    "lightsalmon": "#FFA07A",
    "lightseagreen": "#20B2AA",
    "lightskyblue": "#87CEFA",
    "lightslategrey": "#778899",
    "lightsteelblue": "#B0C4DE",
    "lightyellow": "#FFFFE0",
    "lime": "#00FF00",
    "limegreen": "#32CD32",
    "linen": "#FAF0E6",
    "magenta": "#FF00FF",
    "maroon": "#800000",
    "mediumaquamarine": "#66CDAA",
    "mediumblue": "#0000CD",
    "mediumorchid": "#BA55D3",
    "mediumpurple": "#9370DB",
    "mediumseagreen": "#3CB371",
    "mediumslateblue": "#7B68EE",
    "mediumspringgreen": "#00FA9A",
    "mediumturquoise": "#48D1CC",
    "mediumvioletred": "#C71585",
    "midnightblue": "#191970",
    "mintcream": "#F5FFFA",
    "mistyrose": "#FFE4E1",
    "moccasin": "#FFE4B5",
    "navajowhite": "#FFDEAD",
    "navy": "#000080",
    "oldlace": "#FDF5E6",
    "olive": "#808000",
    "olivedrab": "#6B8E23",
    "orange": "#FFA500",
    "orangered": "#FF4500",
    "orchid": "#DA70D6",
    "palegoldenrod": "#EEE8AA",
    "palegreen": "#98FB98",
    "paleturquoise": "#AFEEEE",
    "palevioletred": "#DB7093",
    "papayawhip": "#FFEFD5",
    "peachpuff": "#FFDAB9",
    "peru": "#CD853F",
    "pink": "#FFC0CB",
    "plum": "#DDA0DD",
    "powderblue": "#B0E0E6",
    "purple": "#800080",
    "rebeccapurple": "#663399",
    "red": "#FF0000",
    "rosybrown": "#BC8F8F",
    "royalblue": "#4169E1",
    "saddlebrown": "#8B4513",
    "salmon": "#FA8072",
    "sandybrown": "#F4A460",
    "seagreen": "#2E8B57",
    "seashell": "#FFF5EE",
    "sienna": "#A0522D",
    "silver": "#C0C0C0",
    "skyblue": "#87CEEB",
    "slateblue": "#6A5ACD",
    "slategrey": "#708090",
    "snow": "#FFFAFA",
    "springgreen": "#00FF7F",
    "steelblue": "#4682B4",
    "tan": "#D2B48C",
    "teal": "#008080",
    "thistle": "#D8BFD8",
    "tomato": "#FF6347",
    "turquoise": "#40E0D0",
    "violet": "#EE82EE",
    "wheat": "#F5DEB3",
    "white": "#FFFFFF",
    "whitesmoke": "#F5F5F5",
    "yellow": "#FFFF00",
    "yellowgreen": "#9ACD32",
}


HUMAN_READABLE_NAMES = {
    "aliceblue": "Alice Blue",
    "antiquewhite": "Antique White",
    "aqua": "Aqua",
    "aquamarine": "Aquamarine",
    "azure": "Azure",
    "beige": "Beige",
    "bisque": "Bisque",
    "black": "Black",
    "blanchedalmond": "Blanched Almond",
    "blue": "Blue",
    "blueviolet": "Blue Violet",
    "brown": "Brown",
    "burlywood": "Burly Wood",
    "cadetblue": "Cadet Blue",
    "chartreuse": "Chartreuse",
    "chocolate": "Chocolate",
    "coral": "Coral",
    "cornflowerblue": "Cornflower Blue",
    "cornsilk": "Cornsilk",
    "crimson": "Crimson",
    "cyan": "Cyan",
    "darkblue": "Dark Blue",
    "darkcyan": "Dark Cyan",
    "darkgoldenrod": "Dark Golden Rod",
    "darkgrey": "Dark Grey",
    "darkgreen": "Dark Green",
    "darkkhaki": "Dark Khaki",
    "darkmagenta": "Dark Magenta",
    "darkolivegreen": "Dark Olive Green",
    "darkorange": "Dark Orange",
    "darkorchid": "Dark Orchid",
    "darkred": "Dark Red",
    "darksalmon": "Dark Salmon",
    "darkseagreen": "Dark Sea Green",
    "darkslateblue": "Dark Slate Blue",
    "darkslategrey": "Dark Slate Grey",
    "darkturquoise": "Dark Turquoise",
    "darkviolet": "Dark Violet",
    "deeppink": "Deep Pink",
    "deepskyblue": "Deep Sky Blue",
    "dimgray": "Dim Gray",
    "dodgerblue": "Dodger Blue",
    "firebrick": "Fire Brick",
    "floralwhite": "Floral White",
    "forestgreen": "Forest Green",
    "fuchsia": "Fuchsia",
    "gainsboro": "Gainsboro",
    "ghostwhite": "Ghost White",
    "gold": "Gold",
    "goldenrod": "Golden Rod",
    "gray": "Gray",
    "green": "Green",
    "greenyellow": "Green Yellow",
    "honeydew": "Honey Dew",
    "hotpink": "Hot Pink",
    "indianred": "Indian Red",
    "indigo": "Indigo",
    "ivory": "Ivory",
    "khaki": "Khaki",
    "lavender": "Lavender",
    "lavenderblush": "Lavender Blush",
    "lawngreen": "Lawn Green",
    "lemonchiffon": "Lemon Chiffon",
    "lightblue": "Light Blue",
    "lightcoral": "Light Coral",
    "lightcyan": "Light Cyan",
    "lightgoldenrodyellow": "Light Golden Rod Yellow",
    "lightgrey": "Light Grey",
    "lightgreen": "Light Green",
    "lightpink": "Light Pink",
    "lightsalmon": "Light Salmon",
    "lightseagreen": "Light Sea Green",
    "lightskyblue": "Light Sky Blue",
    "lightslategrey": "Light Slate Grey",
    "lightsteelblue": "Light Steel Blue",
    "lightyellow": "Light Yellow",
    "lime": "Lime",
    "limegreen": "Lime Green",
    "linen": "Linen",
    "magenta": "Magenta",
    "maroon": "Maroon",
    "mediumaquamarine": "Medium Aquamarine",
    "mediumblue": "Medium Blue",
    "mediumorchid": "Medium Orchid",
    "mediumpurple": "Medium Purple",
    "mediumseagreen": "Medium Sea Green",
    "mediumslateblue": "Medium Slate Blue",
    "mediumspringgreen": "Medium Spring Green",
    "mediumturquoise": "Medium Turquoise",
    "mediumvioletred": "Medium Violet Red",
    "midnightblue": "Midnight Blue",
    "mintcream": "Mint Cream",
    "mistyrose": "Misty Rose",
    "moccasin": "Moccasin",
    "navajowhite": "Navajo White",
    "navy": "Navy",
    "oldlace": "Old Lace",
    "olive": "Olive",
    "olivedrab": "Olive Drab",
    "orange": "Orange",
    "orangered": "Orange Red",
    "orchid": "Orchid",
    "palegoldenrod": "Pale Golden Rod",
    "palegreen": "Pale Green",
    "paleturquoise": "Pale Turquoise",
    "palevioletred": "Pale Violet Red",
    "papayawhip": "Papaya Whip",
    "peachpuff": "Peach Puff",
    "peru": "Peru",
    "pink": "Pink",
    "plum": "Plum",
    "powderblue": "Powder Blue",
    "purple": "Purple",
    "rebeccapurple": "Rebecca Purple",
    "red": "Red",
    "rosybrown": "Rosy Brown",
    "royalblue": "Royal Blue",
    "saddlebrown": "Saddle Brown",
    "salmon": "Salmon",
    "sandybrown": "Sandy Brown",
    "seagreen": "Sea Green",
    "seashell": "Seashell",
    "sienna": "Sienna",
    "silver": "Silver",
    "skyblue": "Sky Blue",
    "slateblue": "Slate Blue",
    "slategrey": "Slate Grey",
    "snow": "Snow",
    "springgreen": "Spring Green",
    "steelblue": "Steel Blue",
    "tan": "Tan",
    "teal": "Teal",
    "thistle": "Thistle",
    "tomato": "Tomato",
    "turquoise": "Turquoise",
    "violet": "Violet",
    "wheat": "Wheat",
    "white": "White",
    "whitesmoke": "White Smoke",
    "yellow": "Yellow",
    "yellowgreen": "Yellow Green",
}


COLOR_FAMILY_ASSOCIATIONS = {
    "aliceblue": [BLUE, WHITE],
    "antiquewhite": [WHITE, BROWN],
    "aqua": [BLUE, None],
    "aquamarine": [BLUE, GREEN],
    "azure": [BLUE, None],
    "beige": [BROWN, None],
    "bisque": [ORANGE, None],
    "black": [BLACK, None],
    "blanchedalmond": [ORANGE, None],
    "blue": [BLUE, None],
    "blueviolet": [PURPLE, None],
    "brown": [BROWN, None],
    "burlywood": [BROWN, None],
    "cadetblue": [GREEN, BLUE],
    "chartreuse": [GREEN, None],
    "chocolate": [BROWN, ORANGE],
    "coral": [ORANGE, PINK],
    "cornflowerblue": [BLUE, None],
    "cornsilk": [YELLOW, None],
    "crimson": [RED, None],
    "cyan": [BLUE, None],
    "darkblue": [BLUE, None],
    "darkcyan": [BLUE, GREEN],
    "darkgoldenrod": [YELLOW, None],
    "darkgrey": [GREY, None],
    "darkgreen": [GREEN, None],
    "darkkhaki": [BROWN, GREEN],
    "darkmagenta": [PURPLE, None],
    "darkolivegreen": [GREEN, None],
    "darkorange": [ORANGE, None],
    "darkorchid": [PURPLE, None],
    "darkred": [RED, None],
    "darksalmon": [PINK, None],
    "darkseagreen": [GREEN, None],
    "darkslateblue": [BLUE, None],
    "darkslategrey": [GREEN, GREY],
    "darkturquoise": [BLUE, GREEN],
    "darkviolet": [PURPLE, None],
    "deeppink": [PINK, None],
    "deepskyblue": [BLUE, None],
    "dimgray": [GREY, None],
    "dodgerblue": [BLUE, None],
    "firebrick": [RED, None],
    "floralwhite": [WHITE, YELLOW],
    "forestgreen": [GREEN, None],
    "fuchsia": [PINK, PURPLE],
    "gainsboro": [GREY, None],
    "ghostwhite": [WHITE, None],
    "gold": [YELLOW, None],
    "goldenrod": [YELLOW, None],
    "gray": [GREY, None],
    "green": [GREEN, None],
    "greenyellow": [GREEN, YELLOW],
    "honeydew": [GREEN, WHITE],
    "hotpink": [PINK, None],
    "indianred": [RED, None],
    "indigo": [PURPLE, None],
    "ivory": [WHITE, None],
    "khaki": [YELLOW, None],
    "lavender": [PURPLE, None],
    "lavenderblush": [PINK, None],
    "lawngreen": [GREEN, None],
    "lemonchiffon": [YELLOW, None],
    "lightblue": [BLUE, None],
    "lightcoral": [PINK, RED],
    "lightcyan": [BLUE, None],
    "lightgoldenrodyellow": [YELLOW, None],
    "lightgrey": [GREY, None],
    "lightgreen": [GREEN, None],
    "lightpink": [PINK, None],
    "lightsalmon": [ORANGE, PINK],
    "lightseagreen": [GREEN, BLUE],
    "lightskyblue": [BLUE, None],
    "lightslategrey": [GREY, None],
    "lightsteelblue": [BLUE, GREY],
    "lightyellow": [YELLOW, None],
    "lime": [GREEN, None],
    "limegreen": [GREEN, None],
    "linen": [PINK, None],
    "magenta": [PINK, None],
    "maroon": [BROWN, None],
    "mediumaquamarine": [GREEN, None],
    "mediumblue": [BLUE, None],
    "mediumorchid": [PURPLE, None],
    "mediumpurple": [PURPLE, None],
    "mediumseagreen": [GREEN, None],
    "mediumslateblue": [PURPLE, BLUE],
    "mediumspringgreen": [GREEN, None],
    "mediumturquoise": [GREEN, BLUE],
    "mediumvioletred": [PINK, None],
    "midnightblue": [BLUE, None],
    "mintcream": [WHITE, GREEN],
    "mistyrose": [PINK, None],
    "moccasin": [YELLOW, None],
    "navajowhite": [ORANGE, None],
    "navy": [BLUE, None],
    "oldlace": [YELLOW, WHITE],
    "olive": [GREEN, None],
    "olivedrab": [GREEN, None],
    "orange": [ORANGE, None],
    "orangered": [RED, None],
    "orchid": [PURPLE, None],
    "palegoldenrod": [YELLOW, None],
    "palegreen": [GREEN, None],
    "paleturquoise": [BLUE, None],
    "palevioletred": [PINK, PURPLE],
    "papayawhip": [YELLOW, None],
    "peachpuff": [ORANGE, None],
    "peru": [BROWN, None],
    "pink": [PINK, None],
    "plum": [PURPLE, None],
    "powderblue": [BLUE, None],
    "purple": [PURPLE, None],
    "rebeccapurple": [PURPLE, None],
    "red": [RED, None],
    "rosybrown": [BROWN, None],
    "royalblue": [BLUE, None],
    "saddlebrown": [BROWN, None],
    "salmon": [ORANGE, PINK],
    "sandybrown": [ORANGE, None],
    "seagreen": [GREEN, None],
    "seashell": [WHITE, None],
    "sienna": [BROWN, None],
    "silver": [GREY, None],
    "skyblue": [BLUE, None],
    "slateblue": [BLUE, PURPLE],
    "slategrey": [GREY, None],
    "snow": [WHITE, None],
    "springgreen": [GREEN, None],
    "steelblue": [BLUE, None],
    "tan": [BROWN, None],
    "teal": [GREEN, BLUE],
    "thistle": [PURPLE, None],
    "tomato": [RED, ORANGE],
    "turquoise": [BLUE, GREEN],
    "violet": [PURPLE, None],
    "wheat": [YELLOW, None],
    "white": [WHITE, None],
    "whitesmoke": [WHITE, GREY],
    "yellow": [YELLOW, None],
    "yellowgreen": [GREEN, None],
}
