from rest_framework.status import *

HTTP_701_BAD_COLOR_CODE = 701
HTTP_702_MISSING_COLOR_CODE = 702
HTTP_703_UNPROCESSABLE_LAB_STR = 703
HTTP_710_ALTCHA_UNABLE_TO_CREATE_CHALLENGE = 710
HTTP_711_ALTCHA_MISSING_PAYLOAD = 711
HTTP_712_ALTCHA_MALFORMED_PAYLOAD = 712
HTTP_713_ALTCHA_VERIFICATION_FAILED = 713

reasons = {
    HTTP_701_BAD_COLOR_CODE: "Invalid Color",
    HTTP_702_MISSING_COLOR_CODE: "Missing Color",
    HTTP_703_UNPROCESSABLE_LAB_STR: "Unprocessable LAB String",
    HTTP_710_ALTCHA_UNABLE_TO_CREATE_CHALLENGE: "Unable to Create Challenge",
    HTTP_711_ALTCHA_MISSING_PAYLOAD: "Missing Altcha Payload",
    HTTP_712_ALTCHA_MALFORMED_PAYLOAD: "Malformed Altcha Payload",
    HTTP_713_ALTCHA_VERIFICATION_FAILED: "Altcha Verification Failed",
}
